### ISSUE TITLE
Deployment Fails In Axway 7.5.3 SP2

### ISSUE THREAD

**Issue by RizkiMufrizal** [Axway-API-Management-Plus/apigw-maven-plugin#58]
Hi...

currently I use Axway api gateway version 7.5.3 with SP2. I have create a policy project, server project and deployment project. I can build policy project and server project but deployment project get error during build process.

File "/home/user/dpl-hello-world/target/temp-scripts/buildfed.py", line 98
[INFO]     except Exception as e:
[INFO]                     ^
[INFO] SyntaxError: mismatched input 'as' expecting COLON
[INFO] --- buildfed.py (End) ------------------------------

is there a solution for the following problem? I think this is due to different jython versions. Can the build deployment process use the latest jython version ?

Thanks

**Comment by mlookaxw** [comment]
Hi @RizkiMufrizal,

yes, you are right. The issue is caused by the Jython version. With API Gateway 7.5.3, Jython 2.5.2 is provided. This version doesn't support the "as" expression.

The build and deployment process use the Jython version provided by the API Gateway and can't be changed. It's because of the tool itself depends on libraries provided by the API Gateway.

**Comment by mlookaxw** [comment]
API Gateway 7.5.3 is not supported by the plugin.
